### ISSUE TITLE
Failure to compile with z3 4.8.5

### ISSUE THREAD

**Issue by fare** [IagoAbal/haskell-z3#20]
Using z3 4.8.5, we get the compilation failure:
```
ld: warning: directory not found for option '-L/nix/store/jf934f80x9m0smswv4352l6mvlra1d8n-gcc-wrapper-7.4.0/lib'
Undefined symbols for architecture x86_64:
 "_Z3_get_error_msg_ex", referenced from:
     _c1b9Y_info in libHSalacrity-0.1.0.0-ttwAml4Vgy2aT7WCYfDT6.a(Compiler.o)
     _c1b9J_info in libHSalacrity-0.1.0.0-ttwAml4Vgy2aT7WCYfDT6.a(Compiler.o)
     _c18Gj_info in libHSz3-408.0-1WFnpTfCBrCIgiQLAlveou.a(Base.o)
     _c18Ig_info in libHSz3-408.0-1WFnpTfCBrCIgiQLAlveou.a(Base.o)
     _c18Ng_info in libHSz3-408.0-1WFnpTfCBrCIgiQLAlveou.a(Base.o)
     _c18Q9_info in libHSz3-408.0-1WFnpTfCBrCIgiQLAlveou.a(Base.o)
     _c1ap4_info in libHSz3-408.0-1WFnpTfCBrCIgiQLAlveou.a(Base.o)
     ...                    
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
```
(The above is the error using clang on a mac, but a similar error happens using gcc on linux.)

**Comment by AlexKnauth** [comment]
Is this error coming from `Z3/Base/C.hsc` line 1457?
https://github.com/IagoAbal/haskell-z3/blob/5023693a5aff76ffca982d32c525a33a7b1d2ce5/src/Z3/Base/C.hsc#L1456-L1458

**Comment by AlexKnauth** [comment]
It looks like Z3's C API stopped supporting the `Z3_get_error_msg_ex` function on this commit:

> overhaul of error messages. Add warning in dimacs conversion

https://github.com/Z3Prover/z3/commit/1eb8ccad59b8ea2c12b1ec8e7e712c7891b252d0#diff-d6c80d51fca9ba3afd43693f09f35c1dL5335

**Comment by IagoAbal** [comment]
Hi @fare, thanks for reporting. I'll take a look at your proposed patch to fix this.
